import { z } from 'zod';
import { PreferencesSchema, MealPlanSchema } from './contracts';

// ==========================================
// Database Schemas (Persistence Layer)
// ==========================================

export const SavedPlanSchema = z.object({
  id: z.number().int().positive().optional(), // Generated by DB
  shortCode: z.string().length(6), // Public access code
  mealPlan: MealPlanSchema,
  preferences: PreferencesSchema,
  createdAt: z.date().optional(),
  expiresAt: z.date().optional(),
});

export type SavedPlan = z.infer<typeof SavedPlanSchema>;
