/**
 * Text Formatter Utility
 * 
 * Converts basic Markdown formatting to HTML for safe rendering in React.
 * Handles bold, italic, and other common formatting patterns generated by AI.
 * 
 * Usage:
 * import { formatText } from './utils/textFormatter';
 * <p dangerouslySetInnerHTML={{ __html: formatText(text) }} />
 */

/**
 * Convert basic Markdown formatting to HTML
 * @param {string} text - Text with Markdown formatting (e.g., **bold**, *italic*)
 * @returns {string} HTML-formatted text
 */
export function formatText(text) {
  if (!text || typeof text !== 'string') return text;
  
  // Escape any existing HTML to prevent XSS
  let formatted = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  
  // Convert **bold** to <strong>
  formatted = formatted.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  
  // Convert *italic* (but not ** which is already converted)
  formatted = formatted.replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, '<em>$1</em>');
  
  // Convert line breaks to <br> if needed
  // formatted = formatted.replace(/\n/g, '<br>');
  
  return formatted;
}

/**
 * Strip all Markdown formatting and return plain text
 * @param {string} text - Text with Markdown formatting
 * @returns {string} Plain text without formatting
 */
export function stripMarkdown(text) {
  if (!text || typeof text !== 'string') return text;
  
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')  // Remove **bold**
    .replace(/\*(.+?)\*/g, '$1')      // Remove *italic*
    .replace(/`(.+?)`/g, '$1')        // Remove `code`
    .replace(/~~(.+?)~~/g, '$1');     // Remove ~~strikethrough~~
}
